name: flutter_pusher
description: A Flutter plugin.
version: 1.0.0
homepage: https://github.com/koorosh-k98/flutter_pusher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  json_annotation: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ninjasolutions.pusher
        pluginClass: PusherPlugin
